### ISSUE TITLE
Starting child process with 'node index.js'

### ISSUE THREAD

**Issue by raulvillora** [bq/bitbloq-frontend#64]
> Bitbloq-Server@1.2.2 start /Users/raulvilloravalencia/Documents/bitbloq-backend
> supervisor index.js

Running node-supervisor with
  program 'index.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node index.js'
Watching directory '/Users/raulvilloravalencia/Documents/bitbloq-backend' for changes.
Press rs for restarting the process.
Error retrieving stats for file: /Users/raulvilloravalencia/Documents/bitbloq-backend/node_modules/.bin/pbjs
Error retrieving stats for file: /Users/raulvilloravalencia/Documents/bitbloq-backend/node_modules/.bin/window-size
^CReceived SIGINT, killing child process...
Parent process exiting, terminating child...
Rauls-MacBook-Pro:bitbloq-backend raulvilloravalencia$ hola 2
bash: hola: command not found
Rauls-MacBook-Pro:bitbloq-backend raulvilloravalencia$ npm start

> Bitbloq-Server@1.2.2 start /Users/raulvilloravalencia/Documents/bitbloq-backend
> supervisor index.js

Running node-supervisor with
  program 'index.js'
  --watch '.'
  --extensions 'node,js'
  --exec 'node'

Starting child process with 'node index.js'
Watching directory '/Users/raulvilloravalencia/Documents/bitbloq-backend' for changes.
Press rs for restarting the process.
Error retrieving stats for file: /Users/raulvilloravalencia/Documents/bitbloq-backend/node_modules/.bin/pbjs
Error retrieving stats for file: /Users/raulvilloravalencia/Documents/bitbloq-backend/node_modules/.bin/window-size
module.js:529
    throw err;
    ^

Error: Cannot find module './config/config.json'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raulvilloravalencia/Documents/bitbloq-backend/app/res/config.js:3:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raulvilloravalencia/Documents/bitbloq-backend/app/app.js:11:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
Program node index.js exited with code 1

Starting child process with 'node index.js'
module.js:529
    throw err;
    ^

Error: Cannot find module './config/config.json'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raulvilloravalencia/Documents/bitbloq-backend/app/res/config.js:3:18)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/raulvilloravalencia/Documents/bitbloq-backend/app/app.js:11:14)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
Program node index.js exited with code 1

**Comment by tocalvo** [comment]
Hi @raulvillora , you need to create a config.json file inside the app/res/config folder with the backend enviroment configuration. 

This is a template that you can modify to add your config, like the mongodb config, to simple test you just need to add the database, and can ignore the gcloud config and the emails.

{
    "env": "local",
    "gcloud": {
        "projectId": "",
        "keyFilename": ""
    },
    "cloudStorageBucket": "",

    "client_domain": "http://localhost:9000",
    "secrets": {
        "session": ""
    },
    "port": 8000,

    "ip": "0.0.0.0",

    "mongo": {
        "uri": "mongodb://mongourl/bitbloq",
    },
    "seedDB": false,
    "mailer": {
        "auth": {
            "user": "",
            "pass": ""
        },
        "defaultFromAddress": "Test <test@gmail.com>"
    },
    "supportEmail": "test@gmail.com",
    "userRoles": [
        "guest",
        "user",
        "admin"
    ]

}

**Comment by raulvillora** [comment]
Thank you so much. 

I was thinking about including to the database all the users who have been authenticated via Auth0.

What do you recommend to use: mongoDB, Auth0 ( authenticating user and including them into the Auth0 database) or another service?
